version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  build:
    docker:
      - image: cimg/node:22.11
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Type check
          command: npm run lint
      - run:
          name: Build
          command: npm run build

workflows:
  build:
    jobs:
      - build
